export const MEDICINES_LIST = [
  "Paracetamol", "Amoxicillin", "Penicillin", "Azithromycin", "Metformin", "Cetirizine",
  "Ibuprofen", "Omeprazole", "Pantoprazole", "Diclofenac", "Amlodipine",
  "Losartan", "Atorvastatin", "Rosuvastatin", "Levothyroxine", "Glimepiride",
  "Ciprofloxacin", "Levofloxacin", "Doxycycline", "Cephalexin", "Metronidazole", "Ondansetron",
  "Domperidone", "Rabeprazole", "Montelukast", "Levocetirizine", "Aspirin",
  "Clopidogrel", "Telmisartan", "Olmesartan", "Teneligliptin", "Vildagliptin",
  "Sitagliptin", "Gliclazide", "Pioglitazone", "Gabapentin", "Pregabalin",
  "Mecobalamin", "Vitamin D3", "Calcium", "Iron", "Folic Acid",
  "Salbutamol", "Budesonide", "Formoterol", "Fluticasone", "Tamsulosin",
  "Finasteride", "Sildenafil", "Tadalafil", "Fluconazole", "Itraconazole",
  "Ketoconazole", "Clotrimazole", "Mupirocin", "Fusidic Acid", "Hydrocortisone",
  "Betamethasone", "Clobetasol", "Permethrin", "Albendazole", "Ivermectin",
  "Dexamethasone", "Prednisolone", "Methylprednisolone", "Deflazacort", "Aceclofenac",
  "Etoricoxib", "Tramadol", "Tapentadol", "Ranitidine", "Famotidine",
  "Sucralfate", "Ursodeoxycholic Acid", "Lactulose", "Bisacodyl", "Loperamide",
  "Racecadotril", "Saccharomyces boulardii", "Bacillus clausii", "ORS", "Zinc",
  "Vitamin C", "B-Complex", "Alpha Lipoic Acid", "Cilostazol", "Pentoxifylline",
  "Flunarizine", "Propranolol", "Metoprolol", "Bisoprolol", "Carvedilol",
  "Amiodarone", "Digoxin", "Warfarin", "Acenocoumarol", "Rivaroxaban",
  "Apixaban", "Dabigatran", "Enoxaparin", "Heparin", "Insulin"
];
